### ISSUE TITLE
handle not available models

### ISSUE THREAD

**Issue by araschke** [abz-conf/abz-conf.github.io#32]
if models of a case study are not publicly available, a text like "please contact authors" shall be added. 

At this part: 
![grafik](https://user-images.githubusercontent.com/2619952/184361527-330811fe-a42c-4be8-80f0-26b73b5e91e2.png)
it should not be stated "not available" but some contact information of the authors. (something like "please contact authors" with a link provided.

**Comment by nksingh-n7** [comment]
abz14, abz16, abz18 and abz20 case studies are updated. "Please contact authors" is added and the required authors emails are provided.

**Comment by araschke** [comment]
done
