### ISSUE TITLE
introduce generic e-mail-address

### ISSUE THREAD

**Issue by araschke** [abz-conf/abz-conf.github.io#38]
We want to create a forwarding from e.g. info@abz-conf.org to abz@uni-ulm.de where the second is a mailing list with arbitrary many members. This could be achieved by providing the right configuration of the MX-Record for the abz-conf.org domain and the following service https://improvmx.com/ 
The free plan should be enough. 

- [x] create `abz@uni-ulm.de` first (by @araschke)
- [x] create alias and update DNS with MX record (by @ppaulweber)

**Comment by ppaulweber** [comment]
@araschke did you create the mail address at the university? If so, I can install the forwarding.

**Comment by ppaulweber** [comment]
I've created the forwarding and added the MX records to the DNS setup and I'Ve checked the setup with a small test mail.
